name: 'S3 upload'
description: 'Github action to upload to S3 and add a version to the name'
author: 'Fixter'
inputs:
  aws-access-key-id:
    description: 'AWS access key id'
    required: true
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true
  aws-region:
    description: 'AWS region'
    default: 'eu-west-1'
    required: false
  github_ref:
    description: 'Reference to the branch or tag beeing built'
    required: false
  bucket_name:
    description: 'Name of the bucket'
    required: true
  bucket_path:
    description: 'Upload path in the bucket'
    default: ''
    required: false
  no_release_path:
    description: 'Do not append release version path to the bucket_path'
    default: ''
    required: false
  target:
    description: 'File to upload'
    required: false
  target_dir:
    description: 'Directory to upload'
    required: false
  sync_options:
    description: 'additional options for `aws s3 sync`'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
    AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
    GITHUB_REF: ${{ inputs.github_ref }}
    BUCKET_NAME: ${{ inputs.bucket_name }}
    BUCKET_PATH: ${{ inputs.bucket_path }}
    NO_RELEASE_PATH: ${{ inputs.no_release_path }}
    TARGET: ${{ inputs.target }}
    TARGET_DIR: ${{ inputs.target_dir }}
    SYNC_OPTIONS: ${{ inputs.sync_options }}
